# -*- coding: utf-8 -*-
"""Consumer Behavior Analysis & Predictive Modeling.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gnJIkT4pw_PkhcG8gC3vX5ACNTI6Noc2
"""

import kagglehub

# Download latest version
path = kagglehub.dataset_download("ranaghulamnabi/shopping-behavior-and-preferences-study")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix

df = pd.read_csv("/kaggle/input/shopping-behavior-and-preferences-study/shopping_behavior_updated.csv")

print("Dataset Shape:", df.shape)

print("\nMissing Values:\n", df.isnull().sum())

display(df.head(3))

category_metrics = df.groupby('Category').agg({
    'Customer ID': 'count',                 # Total Sales Volume
    'Purchase Amount (USD)': ['sum', 'mean'], # Total Revenue & Avg Order Value
    'Review Rating': 'mean'                 # Customer Satisfaction
}).reset_index()

# Clean up column names
category_metrics.columns = ['Category', 'Total_Sales_Count', 'Total_Revenue', 'Avg_Order_Value', 'Avg_Rating']
category_metrics = category_metrics.sort_values(by='Total_Revenue', ascending=False)

print("--- Table 1: Category Performance ---")
display(category_metrics)

seasonal_metrics = df.groupby('Season')['Purchase Amount (USD)'].sum().reset_index()
seasonal_metrics = seasonal_metrics.sort_values(by='Purchase Amount (USD)', ascending=False)

print("\n--- Table 2: Seasonal Revenue ---")
display(seasonal_metrics)

# Create Age Groups
df['Age_Group'] = pd.cut(df['Age'], bins=[18, 30, 45, 60, 100], labels=['18-30', '31-45', '46-60', '60+'])

demographic_metrics = df.groupby(['Age_Group', 'Gender'])['Purchase Amount (USD)'].mean().unstack()

print("\n--- Table 3: Avg Spend by Age & Gender ---")
display(demographic_metrics)

# 1. Select numeric features for clustering
features = df[['Age', 'Purchase Amount (USD)', 'Review Rating', 'Previous Purchases']]

# 2. Scale the data (Standardization is crucial for K-Means)
scaler = StandardScaler()
features_scaled = scaler.fit_transform(features)

# 3. Apply K-Means (Let's assume 4 clusters for this demo)
kmeans = KMeans(n_clusters=4, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(features_scaled)

# 4. Analyze the Clusters
cluster_summary = df.groupby('Cluster')[['Age', 'Purchase Amount (USD)', 'Review Rating', 'Previous Purchases']].mean()
print("\n--- Advanced: Hidden Customer Segments ---")
display(cluster_summary)

# Visualizing the segments
plt.figure(figsize=(10, 6))
sns.scatterplot(data=df, x='Previous Purchases', y='Purchase Amount (USD)', hue='Cluster', palette='viridis', s=60)
plt.title('Customer Segments based on Loyalty & Spending')
plt.show()



"""# Task
Calculate the correlation matrix for the numerical columns (Age, Purchase Amount (USD), Review Rating, Previous Purchases) in the `df` DataFrame, visualize it as a heatmap with annotations, and generate histograms for each of these columns. Finally, summarize the insights gained from these visualizations.

## Calculate Correlation Matrix

### Subtask:
Calculate the correlation matrix for the numerical columns in the DataFrame.

**Reasoning**:
To calculate the correlation matrix, I need to select the specified numerical columns from the DataFrame and then apply the `.corr()` method to them.
"""

numerical_cols = ['Age', 'Purchase Amount (USD)', 'Review Rating', 'Previous Purchases']
correlation_matrix = df[numerical_cols].corr()
print("Correlation Matrix:")
display(correlation_matrix)

"""**Reasoning**:
Now that the correlation matrix has been calculated, I will visualize it as a heatmap to easily interpret the relationships between the numerical variables.


"""

plt.figure(figsize=(8, 6))
sns.heatmap(correlation_matrix, annot=True, cmap='coolwarm', fmt=".2f")
plt.title('Correlation Matrix of Numerical Features')
plt.show()

"""**Reasoning**:
To understand the distribution of each numerical feature, I will generate histograms for 'Age', 'Purchase Amount (USD)', 'Review Rating', and 'Previous Purchases'.


"""

plt.figure(figsize=(15, 10))
for i, col in enumerate(numerical_cols):
    plt.subplot(2, 2, i + 1)
    sns.histplot(df[col], kde=True, bins=20)
    plt.title(f'Distribution of {col}')
    plt.xlabel(col)
    plt.ylabel('Frequency')
plt.tight_layout()
plt.show()

"""### Insights from Correlation Matrix and Histograms

**Correlation Matrix Analysis:**
*   The correlation matrix shows very weak linear relationships between 'Age', 'Purchase Amount (USD)', 'Review Rating', and 'Previous Purchases'. Most correlation coefficients are close to zero, indicating that these numerical features do not strongly correlate with each other in a linear fashion. For example, 'Age' has a negligible correlation with 'Purchase Amount (USD)' (-0.01) and 'Review Rating' (-0.02).
*   'Previous Purchases' also shows very little linear correlation with the other variables, with its highest correlation being 0.04 with 'Age'.

**Histograms Analysis:**
*   **Age:** The distribution of 'Age' appears relatively uniform across the defined bins, suggesting a broad range of ages among the customers, without a strong peak in any particular age group.
*   **Purchase Amount (USD):** The 'Purchase Amount (USD)' histogram shows a distribution that is somewhat spread out, but with a slight tendency towards a normal distribution, centered around the mean. There are no extreme outliers or heavy skewness.
*   **Review Rating:** The 'Review Rating' distribution is heavily skewed towards higher ratings, indicating that customers generally provide positive feedback. There are significantly fewer low ratings.
*   **Previous Purchases:** The 'Previous Purchases' histogram indicates a somewhat uniform distribution, with customers having a varied number of previous transactions. There isn't a clear concentration at very low or very high numbers, suggesting a mix of new and loyal customers.

## Final Task

### Subtask:
Summarize the insights gained from the correlation matrix, heatmap, and histograms.

## Summary:

### Data Analysis Key Findings

*   **Weak Linear Correlations:** The correlation matrix reveals very weak linear relationships between 'Age', 'Purchase Amount (USD)', 'Review Rating', and 'Previous Purchases'. Most correlation coefficients are close to zero, with the highest noted correlation being 0.04 between 'Previous Purchases' and 'Age'. For instance, 'Age' correlates with 'Purchase Amount (USD)' at -0.01 and with 'Review Rating' at -0.02, indicating negligible linear interdependence.
*   **Age Distribution:** The distribution of 'Age' is relatively uniform, suggesting a diverse age range among customers without a significant concentration in any specific age group.
*   **Purchase Amount Distribution:** 'Purchase Amount (USD)' shows a somewhat spread-out distribution with a slight tendency towards a normal shape, centered around its mean.
*   **Review Rating Skewness:** 'Review Rating' is heavily skewed towards higher ratings, indicating a strong prevalence of positive customer feedback.
*   **Previous Purchases Distribution:** 'Previous Purchases' exhibits a somewhat uniform distribution, implying a mix of customers with varied purchase histories, ranging from new to repeat buyers.

### Insights or Next Steps

*   Given the very weak linear correlations between the numerical features, further investigation into non-linear relationships or interactions between these variables, possibly using more advanced modeling techniques, could provide deeper insights.
*   The overwhelmingly positive 'Review Rating' distribution suggests high customer satisfaction, which could be a strong point for marketing or customer retention strategies.
"""